// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2025, 9:45:52 PM
const configMerger = require("D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/plugins/**/*.{js,ts,mjs}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/composables/**/*.{js,ts,mjs}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/utils/**/*.{js,ts,mjs}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/ThuyTinhNgoc/Client-ThuyTinhNgoc/app.config.{js,ts,mjs}"] } }));

module.exports = config
