// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/GHN/get_districts': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/GHN/get_districts').default>>>>
    }
    '/api/GHN/get_provinces': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/GHN/get_provinces').default>>>>
    }
    '/api/GHN/get_service': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/GHN/get_service.post').default>>>>
    }
    '/api/GHN/get_wards': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/GHN/get_wards').default>>>>
    }
    '/api/GHN/shipping_fee': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/GHN/shipping_fee.post').default>>>>
    }
    '/api/imgbb': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/imgbb').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}